
package com.pmarlen.digifactws.production;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CFD", targetNamespace = "https://cfd.sicofi.com.mx", wsdlLocation = "https://cfd.sicofi.com.mx/sicofiWSv2/cfd.asmx?WSDL")
public class CFD
    extends Service
{

    private final static URL CFD_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.pmarlen.digifactws.production.CFD.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.pmarlen.digifactws.production.CFD.class.getResource(".");
            url = new URL(baseUrl, "https://cfd.sicofi.com.mx/sicofiWSv2/cfd.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://cfd.sicofi.com.mx/sicofiWSv2/cfd.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CFD_WSDL_LOCATION = url;
    }

    public CFD(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CFD() {
        super(CFD_WSDL_LOCATION, new QName("https://cfd.sicofi.com.mx", "CFD"));
    }

    /**
     * 
     * @return
     *     returns CFDSoap
     */
    @WebEndpoint(name = "CFDSoap")
    public CFDSoap getCFDSoap() {
        return super.getPort(new QName("https://cfd.sicofi.com.mx", "CFDSoap"), CFDSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CFDSoap
     */
    @WebEndpoint(name = "CFDSoap")
    public CFDSoap getCFDSoap(WebServiceFeature... features) {
        return super.getPort(new QName("https://cfd.sicofi.com.mx", "CFDSoap"), CFDSoap.class, features);
    }

}
