
package com.pmarlen.digifactws.production;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CFDSoap", targetNamespace = "https://cfd.sicofi.com.mx")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CFDSoap {


    /**
     * 
     * @param xmlAddenda
     * @param datosCFD
     * @param usuario
     * @param impuestos
     * @param receptor
     * @param conceptos
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraCFD", action = "https://cfd.sicofi.com.mx/GeneraCFD")
    @WebResult(name = "GeneraCFDResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraCFD", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.GeneraCFD")
    @ResponseWrapper(localName = "GeneraCFDResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.GeneraCFDResponse")
    public String generaCFD(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "DatosCFD", targetNamespace = "https://cfd.sicofi.com.mx")
        DatosCFD datosCFD,
        @WebParam(name = "Receptor", targetNamespace = "https://cfd.sicofi.com.mx")
        Receptor receptor,
        @WebParam(name = "Conceptos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType conceptos,
        @WebParam(name = "Impuestos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType impuestos,
        @WebParam(name = "XMLAddenda", targetNamespace = "https://cfd.sicofi.com.mx")
        String xmlAddenda);

    /**
     * 
     * @param xmlAddenda
     * @param datosCFD
     * @param usuario
     * @param impuestos
     * @param receptor
     * @param conceptos
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraCFDX", action = "https://cfd.sicofi.com.mx/GeneraCFDX")
    @WebResult(name = "GeneraCFDXResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraCFDX", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.GeneraCFDX")
    @ResponseWrapper(localName = "GeneraCFDXResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.GeneraCFDXResponse")
    public String generaCFDX(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "DatosCFD", targetNamespace = "https://cfd.sicofi.com.mx")
        ObjetoX datosCFD,
        @WebParam(name = "Receptor", targetNamespace = "https://cfd.sicofi.com.mx")
        ObjetoX receptor,
        @WebParam(name = "Conceptos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType conceptos,
        @WebParam(name = "Impuestos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType impuestos,
        @WebParam(name = "XMLAddenda", targetNamespace = "https://cfd.sicofi.com.mx")
        String xmlAddenda);

    /**
     * 
     * @param xmlAddenda
     * @param datosCFD
     * @param complemento
     * @param coComplemento
     * @param usuario
     * @param impuestos
     * @param receptor
     * @param conceptos
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraCFDDetallista", action = "https://cfd.sicofi.com.mx/GeneraCFDDetallista")
    @WebResult(name = "GeneraCFDDetallistaResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraCFDDetallista", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.GeneraCFDDetallista")
    @ResponseWrapper(localName = "GeneraCFDDetallistaResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.GeneraCFDDetallistaResponse")
    public String generaCFDDetallista(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "DatosCFD", targetNamespace = "https://cfd.sicofi.com.mx")
        DatosCFD datosCFD,
        @WebParam(name = "Receptor", targetNamespace = "https://cfd.sicofi.com.mx")
        Receptor receptor,
        @WebParam(name = "Conceptos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType conceptos,
        @WebParam(name = "Impuestos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType impuestos,
        @WebParam(name = "XMLAddenda", targetNamespace = "https://cfd.sicofi.com.mx")
        String xmlAddenda,
        @WebParam(name = "Complemento", targetNamespace = "https://cfd.sicofi.com.mx")
        String complemento,
        @WebParam(name = "COComplemento", targetNamespace = "https://cfd.sicofi.com.mx")
        String coComplemento);

    /**
     * 
     * @param xmlAddenda
     * @param concepto
     * @param datosCFD
     * @param usuario
     * @param receptor
     * @param contrasena
     * @param impuesto
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraCFD_1_Concepto", action = "https://cfd.sicofi.com.mx/GeneraCFD_1_Concepto")
    @WebResult(name = "GeneraCFD_1_ConceptoResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraCFD_1_Concepto", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.GeneraCFD1Concepto")
    @ResponseWrapper(localName = "GeneraCFD_1_ConceptoResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.GeneraCFD1ConceptoResponse")
    public String generaCFD1Concepto(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "DatosCFD", targetNamespace = "https://cfd.sicofi.com.mx")
        DatosCFD datosCFD,
        @WebParam(name = "Receptor", targetNamespace = "https://cfd.sicofi.com.mx")
        Receptor receptor,
        @WebParam(name = "Concepto", targetNamespace = "https://cfd.sicofi.com.mx")
        Concepto concepto,
        @WebParam(name = "Impuesto", targetNamespace = "https://cfd.sicofi.com.mx")
        Impuesto impuesto,
        @WebParam(name = "XMLAddenda", targetNamespace = "https://cfd.sicofi.com.mx")
        String xmlAddenda);

    /**
     * 
     * @param serie
     * @param folio
     * @param usuario
     * @param statusfact
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CambiaStatusFact", action = "https://cfd.sicofi.com.mx/CambiaStatusFact")
    @WebResult(name = "CambiaStatusFactResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "CambiaStatusFact", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.CambiaStatusFact")
    @ResponseWrapper(localName = "CambiaStatusFactResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.CambiaStatusFactResponse")
    public String cambiaStatusFact(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "Serie", targetNamespace = "https://cfd.sicofi.com.mx")
        String serie,
        @WebParam(name = "Folio", targetNamespace = "https://cfd.sicofi.com.mx")
        double folio,
        @WebParam(name = "statusfact", targetNamespace = "https://cfd.sicofi.com.mx")
        double statusfact);

    /**
     * 
     * @param usuario
     * @param uuid
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CancelaCFDI", action = "https://cfd.sicofi.com.mx/CancelaCFDI")
    @WebResult(name = "CancelaCFDIResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "CancelaCFDI", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.CancelaCFDI")
    @ResponseWrapper(localName = "CancelaCFDIResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.CancelaCFDIResponse")
    public String cancelaCFDI(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "uuid", targetNamespace = "https://cfd.sicofi.com.mx")
        String uuid);

    /**
     * 
     * @param usuario
     * @param uuid
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AcuseCancelacion", action = "https://cfd.sicofi.com.mx/AcuseCancelacion")
    @WebResult(name = "AcuseCancelacionResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "AcuseCancelacion", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.AcuseCancelacion")
    @ResponseWrapper(localName = "AcuseCancelacionResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.AcuseCancelacionResponse")
    public String acuseCancelacion(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "uuid", targetNamespace = "https://cfd.sicofi.com.mx")
        String uuid);

    /**
     * 
     * @param serie
     * @param folio
     * @param usuario
     * @param contrasena
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GeneraPDF", action = "https://cfd.sicofi.com.mx/GeneraPDF")
    @WebResult(name = "GeneraPDFResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraPDF", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.GeneraPDF")
    @ResponseWrapper(localName = "GeneraPDFResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.GeneraPDFResponse")
    public byte[] generaPDF(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "Serie", targetNamespace = "https://cfd.sicofi.com.mx")
        String serie,
        @WebParam(name = "Folio", targetNamespace = "https://cfd.sicofi.com.mx")
        double folio);

    /**
     * 
     * @param xmlAddenda
     * @param datosCFD
     * @param usuario
     * @param impuestos
     * @param conceptos
     * @param fechaCreacion
     * @param contrasena
     * @param numeroTicket
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "IntroduceDatosTicket", action = "https://cfd.sicofi.com.mx/IntroduceDatosTicket")
    @WebResult(name = "IntroduceDatosTicketResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "IntroduceDatosTicket", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.IntroduceDatosTicket")
    @ResponseWrapper(localName = "IntroduceDatosTicketResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.IntroduceDatosTicketResponse")
    public String introduceDatosTicket(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "DatosCFD", targetNamespace = "https://cfd.sicofi.com.mx")
        DatosCFD datosCFD,
        @WebParam(name = "Conceptos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType conceptos,
        @WebParam(name = "Impuestos", targetNamespace = "https://cfd.sicofi.com.mx")
        ArrayOfAnyType impuestos,
        @WebParam(name = "NumeroTicket", targetNamespace = "https://cfd.sicofi.com.mx")
        String numeroTicket,
        @WebParam(name = "FechaCreacion", targetNamespace = "https://cfd.sicofi.com.mx")
        String fechaCreacion,
        @WebParam(name = "XMLAddenda", targetNamespace = "https://cfd.sicofi.com.mx")
        String xmlAddenda);

    /**
     * 
     * @param usuario
     * @param xml
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraTFD", action = "https://cfd.sicofi.com.mx/GeneraTFD")
    @WebResult(name = "GeneraTFDResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "GeneraTFD", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.GeneraTFD")
    @ResponseWrapper(localName = "GeneraTFDResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.GeneraTFDResponse")
    public String generaTFD(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "xml", targetNamespace = "https://cfd.sicofi.com.mx")
        String xml);

    /**
     * 
     * @param usuario
     * @param uuid
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CancelaTFD", action = "https://cfd.sicofi.com.mx/CancelaTFD")
    @WebResult(name = "CancelaTFDResult", targetNamespace = "https://cfd.sicofi.com.mx")
    @RequestWrapper(localName = "CancelaTFD", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.CancelaTFD")
    @ResponseWrapper(localName = "CancelaTFDResponse", targetNamespace = "https://cfd.sicofi.com.mx", className = "com.pmarlen.digifactws.production.CancelaTFDResponse")
    public String cancelaTFD(
        @WebParam(name = "Usuario", targetNamespace = "https://cfd.sicofi.com.mx")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "https://cfd.sicofi.com.mx")
        String contrasena,
        @WebParam(name = "uuid", targetNamespace = "https://cfd.sicofi.com.mx")
        String uuid);

}
